# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5291b615719e5294e42effdbb1c2a4284f137583c270dceaf6e66089fe2a359dab853a2884cb6b1c34b68db0eda313ca7051ebe17084fd968a4472f26b9c355

test:
  secret_key_base: e88ea668e6d58278b02dfc609448fda22058479c8178a8df48c06e62df229365e211ffa2825b28a80e96c069ff7656c2641d01b3706f9a00c4ac3e2022afb5ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
